import RoadmapCard from "../RoadmapCard";
import Subtitle from "../Subtitle";
import Title from "../Title";

function Roadmap() {
    return (
      <div className="Section Roadmap">
        <Title name="Roadmap" />
        <Subtitle text="fra Haugesund til Trondheim" />
        <div className="roadmap-container">
            <div className="middle-line"></div>
            <RoadmapCard tag="stop0" side="line-left" time="Aug 1997" text="Historien begynner i Haugesund. Tidelig en sommersdag kommer en litt stor baby til verden. I motsetning til mine søstre var jeg en rolig baby som foretrakk å sove mye og spise på kommando. Kanskje det var grunnen?" image="/images/babybilde.JPG" />
            <RoadmapCard tag="stop1" side="line-right" time="BARNDOM" text="På sommeren pleide vi å være på hytta som ligger rett utenfor Haugesund. Der holder også mye av slekten til, som gjorde at det alltid var mye som skjedde. Jeg var glad i å kjøre båt og hadde min egen 'Steady' som jeg fikk kjøre alene. En av mine favorittaktiviteter var softgun-krig sammen med noen kompiser. Da hadde vi laget en bane i skogen hvor vi koste oss utrolig mye." image="/images/barndom.JPG" />
            <RoadmapCard tag="stop2" side="line-left" time="Aug 2013 - Jun 2016" sted="Skeisvang VGS" text="Etter ungdomsskolen så begynte jeg på Skeisvang videregående skole. Hver dag måtte jeg ta bussen i 45 min til skolen, selv om det bare tar 15 min å kjøre direkte. Dermed var det utrolig digg å få lappen og kjøre til skolen selv. Det var også på Skeivang hvor jeg hadde faget IT2 som intoduserte meg til programmering. Etter å ha laget noen spill innså jeg hvor mye man kunne lage med kode." image="/images/skeisvang.jpeg" />
            <RoadmapCard tag="stop3" side="line-right" time="Aug 2016 - Mai 2017" sted="Nordfjord FHS" text="Etter VGS så gikk jeg et år på folkehøyskole. Valget landet på Nordfjord da de hadde linjen Jakt og Fiske i tillegg til et godt rykte. Året oversteg forventningene. Jeg hadde et helt magisk år ute i naturen og fikk noen helt spesielle vennskap. I løpet av året fikk jeg et godt pusterom til å bli bedre kjent med meg selv og historier som jeg elsker å tenke tilbake på." image="/images/nordfjord.jpeg" />
            <RoadmapCard tag="stop4" side="line-left" time="Aug 2017" sted="NTNU, Trondheim" text="Etter folkehøyskolen så søkte jeg Datateknologi på NTNU etter å ha blitt inspirert av IT2. Jeg gledet meg til studenttiden og var klar for nye eventyr. Etter sommeren flyttet jeg inn i kollektiv med ukjente studenter på Berg studentby. Etter kort tid så var det utrolig god stemning i kollektivet og vi gjorde mye sammen. En av roomiene introduserte meg musikk (Hip-Hop og Rap), hvor mange kvelder tok vi frem whisky og hørte på musikken sammen. Han er en av mine nærmeste venner idag. " image="/images/hovedbygget.jpeg" />
            <RoadmapCard tag="stop5" side="line-right" time="Aug 2017" sted="Start NTNU" text="Jeg var gira på å bli med i et studentverv og søkte Start NTNU. Et av mine beste valg noensinne. Her ble jeg tatt med på et eventyr som jeg ikke kunne forestilt meg. Her ble jeg kjent med så mange engasjerte og flinke studenter, og når jeg sier engasjert så snakker jeg om typen personer som lyser opp dagen din. Og jeg hadde 50 stk av dem. Det var et miljø som ikke bare inkluderte meg, men også utfordret meg hver dag." image="/images/startntnu.jpeg" />
            <RoadmapCard tag="stop6" side="line-left" time="Mai 2018" sted="BRAIN NTNU" text="I løpet av våren så ble jeg kontaktet av en venn for å bli med å høre om et initaiv fra Norwegian Open AI Lab, som resulterte i at vi grunnla en ny studentorganisasjon: BRAIN NTNU. Fokuset vårt er å samle studenter, forskning og nærlingslivet rundt kunstig intilligens. Det var mye organisatork arbeid som måtte legges ned, i tillegg til å prøve å bygge opp en bærekratig orangiasjon. Det har vi greid og nå er BRAIN helt i spydspissen av studentorganiasjoner på NTNU. Her er det bare å følge med hva som skjer videre!" image="/images/brain.jpg" />
            <RoadmapCard tag="stop7" side="line-right" time="Okt 2018" sted="Start Forum" text="En av opplevelsene/utfordringene var på Start Forum, arrangert av Start NTNU. Her hadde jeg teknisk ansvar for Petter Stordalen sitt foredrag, som ikke gikk som det skulle. Han spøkte med meg før arrangementet: 'Hvis det skjer noe så skal jeg dra deg ut på scenen.' Og er det en gang noe skal gå galt så må det jo være denne gangen.. Heldigvis var det ikke min feil men ut på scenen måtte jeg. For en opplevelse!" image="/images/stordalen.png" />
            <RoadmapCard tag="stop8" side="line-left" time="Apr 2019" sted="NGA 2019" text="Rollen min i Start NTNU var blant annet Prosjektleder for Norwegian Game Awards 2019 (NGA). Så sammen med prosjektgruppen min arrangerte vi Norges største spillutviklingskonfereanse for studenter. Premieutdelingen fant sted på Clarion Hotel hvor vi hadde over 300 i publikum. En av de beste minnene fra den prosjektperioden er når vi jobbet sammen så prøvde vi alltid å ha det gøy. En gang så laget vi et tårn av pulter og hoppet ned på en haug saccosekker." image="/images/nga.jpeg" />
            <RoadmapCard tag="stop9" side="line-right" time="Nov 2019" sted="Los Angeles" text="Sammen med noen studiekamerater så satt vi å jobbe mot eksamener før sommeren i 2019. Her begynte vi å dagdrømme oss bort til reisesteder og festivaler. Vi ble så gira at det endte faktisk med at vi booket en tur til LA i eksamensperioden høsten 2019. En uke så vi oss rundt i LA og Hollywood, i tillegg til å dra på festivalen Camp Flog Gnaw. Alt kan skje hvis man er gira på det!" image="/images/hollywood.png" />
            <RoadmapCard tag="stop10" side="line-left" time="Jun 2020" sted="Sandra" text="Så kommer kanskje det beste delen av historien min: Sandra. Det er en egen historie i seg selv som faktisk burde bli film en vakker dag. I juni 2020 så flyttet vi sammen i Trondheim. Vi møttes på ungdomskolen og har egentlig vært knyttet sammen hele livet. Hun er født dagen etter meg på samme sykehus som kanskje vil si at vi møttes heeelt i begynnelsen? Hun har alltid vært min beste venn og vi har det helt fantastisk sammen, med nye eventyr rundt hver sving. " image="/images/sandy.JPG" />
            <RoadmapCard tag="stop11" side="line-right" time="Aug 2021" sted="Master Life" text="Så hvor er jeg nå? Jeg sitter jeg på mastersalen og skriver denne historien. Det er kanskje ikke mange som leser den, men den er faktisk mye til meg selv. Det er kjekt å minnes tilbake på alt som har skjedd de siste årene. Sammen med en kompis så skriver vi nå prosjektoppgaven om sikkerhet og kunstig intelligens. To fagområder vi finner svært interessant og gleder oss til å utforske resten av året. Det er mye lesing for å forstå domenet men til slutt så håper vi å stå igjen med noe som faktisk kan bli brukt videre." image="/images/mastersal.JPG" />
            <RoadmapCard tag="stop12" side="line-left" time="Aug 2022" sted="Stavanger" text="Hva skjer videre? Sandra og jeg tar veien videre mot Stavanger. Det blir et nytt kapittel i eventyret som vi gleder oss til å begynne. Jeg håper at de neste 5 årene blir like fantastiske som de forrige årene har vært for meg." />
        </div>
      </div>
    );
  }
  
  export default Roadmap;